FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.1
ENV xpack.security.enabled=false
ENV discovery.type=single-node
#ADD elasticsearch-mapper-preanalyzed-5.4.0.zip /
#RUN ["bin/elasticsearch-plugin", "install", "file:///elasticsearch-mapper-preanalyzed-5.4.0.zip"]